name: CI

on:
  push:
    branches: [main, Main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: Lint, format, test e build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - run: npm run lint

      - run: npm run format:check

      - run: npm run test:coverage

      - run: npm run build
